### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by ll7** [nautnatic/ans-safety-validation#1]
https://github.com/nautnatic/ans-safety-validation/blob/aba2eeaf96c4e0c5c35c5145a8250d696c80a8af/docs/Usage.md?plain=1#L6-L8

After `catkin_make` I am unable to `source root/devel/setup.sh` because the permission is denied. `exec-container-shell.sh` enters the shell as the user `user` and can't access the `root` directory.

The `home` directory of the `user` does include a `devel` folder. However, if I source `/home/user/devel/setup.sh` my `roslaunch` is unable to find `arena_bringup`.

**Comment by lautermi** [comment]
The documentation in Usage.md wasn't up-to-date. I updated it and also fixed some dynamic dependencies. With these changes, I can build and run everything successfully. You can see my changes in #2.

Can you validate, if it works for you as well? Please make sure to set the environment variable USE_IMAGE_BUILD_CACHE=false with direnv to make sure we have the same setup.
